FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migrations

WORKDIR /app
COPY api/ api/
WORKDIR /app/api

RUN dotnet restore "api.csproj"

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY migrate.sh /migrate.sh
USER root
RUN chmod +x /migrate.sh  # Make script executable
USER app
ENTRYPOINT ["/migrate.sh"]

